### ISSUE TITLE
Custom status column

### ISSUE THREAD

**Issue by vijayanandnandam** [vigetlabs/simplest_status#2]
In our rails app we have numerous statuses for many models. I want to use this gem, but the it accepts `status` as the only column for `statuses`. I  want the ability to configure when using it so that we can use any other columns like `registration_status_id` or `payment_status_id`

**Comment by vijayanandnandam** [comment]
BTW just forked it and trying to implement this functionality

**Comment by rysospicy** [comment]
Thanks for the feedback!  Unless you beat me to it with a pull request, I'll look into this next week.

**Comment by rysospicy** [comment]
This is now implemented in version `1.0.0`.
